export const TYPE_COLOR: { [type: string]: string } = {
  normal: "bg-[#aa9]",
  fire: "bg-[#f42]",
  water: "bg-[#39f]",
  electric: "bg-[#fc3]",
  grass: "bg-[#7c5]",
  ice: "bg-[#6cf]",
  fighting: "bg-[#b54]",
  poison: "bg-[#a59]",
  ground: "bg-[#db5]",
  flying: "bg-[#89f]",
  psychic: "bg-[#f59]",
  bug: "bg-[#ab2]",
  rock: "bg-[#ba6]",
  ghost: "bg-[#66b]",
  dragon: "bg-[#76e]",
  dark: "bg-[#754]",
  steel: "bg-[#aab]",
  fairy: "bg-[#e9e]",
};
